# Generated by Django 3.1.3 on 2020-12-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('BTECH', 'BTECH'), ('BCA', 'BCA'), ('BCOM', 'BCOM'), ('BBA', 'BBA')], max_length=20)),
                ('course_fee', models.DecimalField(decimal_places=1, default=1500, max_digits=8)),
                ('course_duration', models.CharField(max_length=30)),
            ],
        ),
    ]
